### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by orekyuu** [orekyuu/JavaBeamStudio#77]
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/Utils
    at org.controlsfx.tools.Platform.getCurrentPlatform(Platform.java:65)
    at org.controlsfx.tools.Platform.<clinit>(Platform.java:41)
    at org.controlsfx.control.ButtonBar$3.<clinit>(ButtonBar.java:369)
    at org.controlsfx.control.ButtonBar.<init>(ButtonBar.java:369)
    at org.controlsfx.control.ButtonBar.<init>(ButtonBar.java:355)
    at org.controlsfx.control.action.ActionUtils.createButtonBar(ActionUtils.java:429)
    at impl.org.controlsfx.skin.NotificationBar.updatePane(NotificationBar.java:164)
    at impl.org.controlsfx.skin.NotificationBar.<init>(NotificationBar.java:160)
    at org.controlsfx.control.Notifications$NotificationPopupHandler$1.<init>(Notifications.java:332)
    at org.controlsfx.control.Notifications$NotificationPopupHandler.show(Notifications.java:332)
    at org.controlsfx.control.Notifications$NotificationPopupHandler.show(Notifications.java:317)
    at org.controlsfx.control.Notifications.show(Notifications.java:263)
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.Utils
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 19 more

**Comment by orekyuu** [comment]
通知を出そうとするとでるっぽい。

**Comment by orekyuu** [comment]
https://bitbucket.org/controlsfx/controlsfx/issues/576/notifications-broken-on-java-8-u60  
Java8u60で発生するcontrolsfxのバグっぽい。
修正されるまで保留

**Comment by orekyuu** [comment]
https://github.com/orekyuu/JavaBeamStudio/pull/90
